all:
  children:
    ubuntu:
      hosts:
        web01.internal.codetical.com:
        pelican.internal.codetical.com:
        pinas.internal.codetical.com:
        pirateship.internal.codetical.com: